Aerospike Bedrock integration example
aws-samples/aws-generativeai-partner-samples pull request #22
Opened 2024-09-23 21:50 UTC by rahul-aerospike

*Issue #, if available:*

*Description of changes:*
This pull request add example on how to use Aerospike Vector Store(AVS) with Bedrock. Please refer to [AVS page](https://aerospike.com/docs/vector) for more information.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-27 18:01 UTC, ayanray089 reviewed
1.	Please remove hard coded values of secret key, access key from the code. Instead provide proper instructions.
2.	Please provide instructions on how users can install AVS 0.10.1. Please consider that users will not be familiar with Aerospike. The notebook should be self sufficient. Do you have a cloud offering and free trial associated with it? If so, it would be better to include it instead of users going through installation.
3.	Remove hard coded values of AVS_HOST. I think it will change as per environment. Instead provide proper instructions.
4.	Please add a screenshot highlighting the context from raw data, and then print two variables 1/ response without context and 2/ response with context. This will help users to understand the value Aerospike is bringing with RAG.

2024-10-02 15:19 UTC, hev requested changes
@rahul-aerospike this suggestion covers items 2 & 3. Can you help with 1 and 4?

2024-10-02 15:19 UTC, hev commented on aerospike/README.md
> +Follow these [steps](https://aerospike.com/docs/vector/install) to setup Aerospike Vector Store cluster.
```suggestion
If you have a license key, follow these [steps](https://aerospike.com/docs/vector/install) to setup Aerospike Vector Store cluster in your account, or you can [request a free trial](https://aerospike.com/lp/aerospike-vector-search-preview-access/) experience which provides a cloud hosted Aerospike Vector Search endpoint (AVS_HOST below). 
```

2024-10-02 18:25 UTC, hev commented on aerospike/README.md
> +You can set the environment variables in the Jupyter Notebook.
```suggestion
You can set the environment variables in the Jupyter Notebook. Setup your access key and secret key and provide below where it says `YOUR_AWS_ACCESS_KEY` and `YOUR_AWS_SECRET_KEY`
```

2024-10-03 22:03 UTC, rahul-aerospike commented
> 4\. Please add a screenshot highlighting the context from raw data, and then print two variables 1/ response without context and 2/ response with context. This will help users to understand the value Aerospike is bringing with RAG.

Can you please further expand on the "response without context" and "response with context". Not quite sure how would I achieve it.  Can you point me to any example in the repo where the above mentioned variables are printed.

2024-10-14 18:33 UTC, merged